articles/urls.py
from django.urls import path

from .views import (
    article_create_view,
    article_detail_view,
    article_search_view
)

app_name = 'articles'
urlpatterns = [
    path('', article_search_view, name='search'),
    path('create/', article_create_view, name='create'),
    path('<slug:slug>/', article_detail_view, name='detail'),
]

recipes/urls.py
from django.urls import path

from .views import (
    recipe_list_view,
    recipe_detail_view,
    recipe_delete_view,
    recipe_create_view,
    recipe_update_view,
    recipe_detail_hx_view,
    recipe_ingredient_update_hx_view,
    recipe_ingredient_delete_view,
    recipe_ingredient_image_upload_view
)


app_name = 'recipes'
urlpatterns = [
    path("", recipe_list_view, name='list'),
    path("create/", recipe_create_view, name='create'),

    path("hx/<int:id>/", recipe_detail_hx_view, name='hx-detail'),
    path("hx/<int:parent_id>/ingredient/<int:id>/", recipe_ingredient_update_hx_view, name='hx-ingredient-detail'),
    path("hx/<int:parent_id>/ingredient/", recipe_ingredient_update_hx_view, name='hx-ingredient-create'),

    path("<int:parent_id>/image-upload/", recipe_ingredient_image_upload_view),
    path("<int:parent_id>/ingredient/<int:id>/delete/", recipe_ingredient_delete_view, name='ingredient-delete'),
    path("<int:id>/delete/", recipe_delete_view, name='delete'),
    path("<int:id>/edit/", recipe_update_view, name='update'),
    path("<int:id>/", recipe_detail_view, name='detail'),
]

trydjango/urls.py
from django.contrib import admin
from django.urls import include, path

from search.views import search_view

from accounts.views import (
    login_view,
    logout_view,
    register_view,
)

from meals.views import meal_queue_toggle_view
from .views import home_view

urlpatterns = [
    path('', home_view),  # index / home
    path('pantry/recipes/', include('recipes.urls')),
    path('articles/', include('articles.urls')),
    path('meal-toggle/<int:recipe_id>', meal_queue_toggle_view, name='meal-toggle'),
    path('search/', search_view, name='search'),
    path('admin/', admin.site.urls),
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        <script src="https://unpkg.com/htmx.org@1.9.2"></script>
        <link rel="stylesheet" href='{% static "recipes/recipes-htmx.css" %}'/>
    </head>
    <body>

        {% include 'base/navbar.html' %}

        <div class="container">
            <div class="row">
                <div class="col-12">
                    {% block content %}
                    <h3>This will be replaced</h3>
                    {% endblock content %}
                </div>
            </div>
        </div>


        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

        <script>
            document.body.addEventListener("htmx:configRequest", (event)=>{
                event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}'
            })
        </script>

    </body>
</html>

templates/home-view.html
{% extends "base.html" %}

{% block content %}
<h1>{{ title }} - (id: {{ id }})!</h1>
<p> {{ content }}!</p>

<h3>
<a href='{% url "articles:create" %}'>Create Article</a>
<!--<a href='{% url "articles:detail" slug="hello-world" %}'>hello world</a>-->
</h3>

<ul>
    {% for x in object_list %}
        {% if x.title %}
            <li><a href='{{ x.get_absolute_url }}'>{{ x.title }} - {{ x.content }}</a>!</li>
        {% endif %}
    {% endfor%}
</ul>
{% endblock content %}

templates/image-form.html
{% extends "base.html" %}


{% block content %}

<form action="." method="POST" enctype="multipart/form-data"
    hx-post="{{ request.path }}"
    hx-ecoding="multipart/form-data"

>
    {% csrf_token %}
    {{ form.as_p }}
    <button style="margin-top:10px;" type="submit">Upload Image</button>
</form>

{% endblock content %}